### ISSUE TITLE
Not able to use Odata feeds in Excel and Power BI

### ISSUE THREAD

**Issue by kumarvika** [SAP/olingo-jpa-processor-v4#103]
Hi,

Everything thing is working fine except that, I am not able to use feeds in Excel and Power BI. As they have default connector to get feeds from ODATA. Getting "Invalid URI: The hostname could not be parsed." as an error.

I am using a 0.3.7 version.

![error-excel](https://user-images.githubusercontent.com/55437921/77926458-c48d3880-72c3-11ea-8a2a-bf7ffcf1286b.png)

**Comment by wog48** [comment]
Hello,

the problem here is that excel expects absolut links, but olingo produces  by default relative links, see https://issues.apache.org/jira/browse/OLINGO-787.

Up to know it is not possible to switch to absolut path. I prepared an enhancement that you can find in branch [release-0.3.8](https://github.com/SAP/olingo-jpa-processor-v4/tree/feature/release-0.3.8 ). You will find a new method in the service [context builder](https://github.com/SAP/olingo-jpa-processor-v4/blob/feature/release-0.3.8/jpa/odata-jpa-processor/src/main/java/com/sap/olingo/jpa/processor/core/api/JPAODataServiceContext.java): _setUseAbsoluteContextURL_. Provide **true** to switch to absolute path.

Let me know if this works for you

**Comment by kumarvika** [comment]
Thanks, @wog48 I did some workaround.

I created one CustomeProcessor and register that processor into JPAODataGetHandler.

It is giving me the desired response.

Thank you for your response. 

Anyway my in excel I am facing issues with relationship queries so I try the solution given by you.

**Comment by kumarvika** [comment]
Hi @wog48,

It is working now. Thank you very much.
