### ISSUE TITLE
Fields in @MappedSuperclass are not visible

### ISSUE THREAD

**Issue by ejsthier** [SAP/olingo-jpa-processor-v4#105]
The fields from the base class are not visible when you you extend a base class with the @MappedSuperclass annotation.

Your entity doesn't have an id field in $metadata when your entity extends this class:
`@MappedSuperclass
abstract class AbstractEntity : Persistable<Int> {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private var id: Int? = null`

**Comment by wog48** [comment]
In in the $metadata document the sub type does not contains the field of the super type. The sub type only contains the extension. Please have a look at [CSDL: 6 Entity Type](https://docs.oasis-open.org/odata/odata-csdl-xml/v4.01/odata-csdl-xml-v4.01.html#sec_EntityType)

**Comment by dm-ion** [comment]
Looks to me like MappedSuperclass is not currently supported, only have abstract parents which are annotated with @Entity.

Looks like it would be pretty easy to add support for MappedSuperclass. You would need to:

1. In IntermediateSchema.buildEntityTypeList you would have to use jpaMetamode.getManagedTypes (instead of .getEntities)

2. Fix the knock on effects from that. Namely you would have to extend the JPAEdmNameBuilder to support the MappedSuperclassType instead of using EntityType. So You'd need to figure out an appropriate name to use here as MappedSuperclassType doesn't have a .getName like EntityType does.

**Comment by dm-ion** [comment]
Hey @wog48 I think you can close this issue now as your latest enhancement seems to work great. 👍

**Comment by dm-ion** [comment]
@wog48 I was taking a look at this today, one thing I noticed with your implementation is that it only supports one mapped super class parent, JPA allows you to have multiple.

So if you were to have say:

AbstractEntity (@MappedSuperclass)
    - AbstractTimeStampable (@MappedSuperclass)
        - Entity (@Entity)

You would not get fields from AbstractEntity.
