### ISSUE TITLE
Estimate on when Enums will be supported?

### ISSUE THREAD

**Issue by ericraskin** [SAP/olingo-jpa-processor-v4#13]
Hi:

I know that JPA Enums are on your road map.  Any idea when they will be supported?

   Eric

**Comment by wog48** [comment]
JPA Enums  have only be taken into account during a first investigation for OData Enumeration Types,  as from my point of view enumerations makes only sense if the values can be given already by the client. This would reduce the value for EnumType to the default ORDINAL.
Would that fits to your use case?

Oliver

**Comment by wog48** [comment]
Hello Eric,

I have created an implementation for enumerations. You can find a small description how they work here:[Enumeration Types](https://github.com/SAP/olingo-jpa-processor-v4/blob/develop/jpa-tutorial/Tutorials/Metadata/1-12-EnumerationTypes.md).

I hope it fits your needs.
Oliver

**Comment by wog48** [comment]
@ericraskin 
Hello Eric,
in case you have any problem or recommendation please open a new issue.

Regards,
Oliver

**Comment by ozzioma** [comment]
Hi,
Thanks for the awesome work!
I'm having mapping errors with enums.

My JPA models do not use `@EdmEnumeration`, since I have them imported as a dependency.
```
@EdmEnumeration()
public enum DemoEntity {
  A, B, C;
}
```


Is it possible to skip the use of yet another annotation and use Reflections to build the schema for enum fields?
Like so

```
//for (Class<?> enumeration : reflections.getTypesAnnotatedWith(EdmEnumeration.class))
        for (Class<?> enumeration : reflections.getTypesAnnotatedWith(Column.class))
      {
        if (enumeration.isEnum())
        {
          @SuppressWarnings("unchecked")
          final IntermediateEnumerationType e = new IntermediateEnumerationType(nameBuilder, (Class<T>) enumeration);
          enumList.put(e.getInternalName(), e);
        }
      }
```
You don't really need a new annotation to support enums, as you can use the Reflections library to get the fields that are enum types.
This is because, you can expect that at a mininum JPA entity model classes will have the `@Column` annotation. I don't know if that does not suffice.

Is it possible to use `@Column`  and the `.isEnum()` class method to filter out enum fields?
With this approach, you can 2 sensible defaults for enum fields, like this:
One for fields with `@Enumerated(value = EnumType.STRING)`  and another for fields with `@Enumerated(value = EnumType.ORDINAL).`

This way if the @Enumerated annotation is not found, the default becomes `@Enumerated(value = EnumType.ORDINAL).`

I think this should be the default approach for supporting enum properties.

Any thoughts?

Thanks.
