### ISSUE TITLE
filter & expand is not working

### ISSUE THREAD

**Issue by chentopf** [SAP/olingo-jpa-processor-v4#21]
Hi,
When i am calling:
/Scans?$filter=Team/Level eq 4&$expand=Team
im getting:
OData Library: An exception without message text was thrown.

any idea why?

**Comment by wog48** [comment]
Hello,
I assume that the Team relation is a to one relation, otherwise you would get a 

> The URI is malformed.

exception and would need to use a lambda expression. When trying to reproduce the problem I got the following error message: 

> "while trying to invoke the method java.util.Collection.toArray() of a null object loaded from local variable 'c'"

The error is thrown in JPANavigationOperation. getExistsQuery(). The problem occurs in generating the expand query. Expand queries are generated as separate queries that use the parent query as a sub select, which fails it the parent query has a sub select in itself.

**Comment by chentopf** [comment]
Do you plan to solve this issue in the future?

**Comment by wog48** [comment]
Yes, it will be fixed in the next release, but I can not give an exact date.

**Comment by wog48** [comment]
The new version 0.2.6 shall fix the problem

**Comment by chentopf** [comment]
When you release 0.2.6?

**Comment by wog48** [comment]
If you pull the repo you get version 0.2.6
