### ISSUE TITLE
Unable to sort on fields that are part of composite key

### ISSUE THREAD

**Issue by BlueCatSpy** [SAP/olingo-jpa-processor-v4#23]
While it is possible to filter on a field that is part of a composite key, trying to order by it will raise an exception with a message that looks like the following: Property for 'foo' not found at 'bar'.

A filter expression would filter correctly the foo field to 'bar.id.foo' while the order by is looking for 'bar.foo' which doesn't exist.

**Comment by wog48** [comment]
Hello,
In my opinion the behavior of _order by_ is the correct one and what you describe for _filter_ is wrong.
Let me explain why:

I assume that your jpa entity look like follows:
```Java
@Entity
public class Bar {

  @EmbeddedId
  private BarPK id;
  ...
}
```
```Java
@Embeddable
public class BarPK 

  @Column(name = "\"...\"", length = ...)
  private String foo;
  ...
}
```
For my understanding the OData specification does not allow a complex type. E.g. [Part 3,  8.2 Element edm:Key](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part3-csdl/odata-v4.0-errata03-os-part3-csdl-complete.html#_Toc453752555) states:

> The properties that compose the key MUST be non-nullable and typed with an enumeration type, one of the following primitive types, or a type definition based on one of these primitive types:
...
 
That's why `IntermediateEntityType.getKey()` "flats" embedded ids and the metadata document should look like:

```XML
<EntityType Name="Bar">
    <Key>
        <PropertyRef Name="Foo"/>
        ...
    </Key>
    ...
</EntityType>
```
I tried to reproduce the behavior you describe, but I was not able to. Please give my more details, so I can find out whats going wrong.
